much improve new script

diff --git a/ns b/ns
--- a/ns
+++ b/ns
@@ -4,12 +4,22 @@ IFS=$'\n\t'
 
 
 function new_script () {
-  local script_name=$1
-  local script_path="$HOME/Code/scripts/$script_name"
-  echo "#!/bin/bash
+  local script_path="$1"
+
+  cat >> "$script_path" <<EOF
+#!/bin/bash
 set -euo pipefail
-IFS=\$'\\n\\t'" >> "$script_path"
+IFS=$'\n\t'
+EOF
   chmod +x "$script_path"
 }
 
-new_script "$1"
+script_name=$1
+script_path="$HOME/Code/scripts/$script_name"
+if [ -e "$script_path" ]
+then
+  new_script "$1"
+else
+  echo "fuck you, $script_path already exists! Aborting!"
+  exit 1
+fi
